# Generated by Django 4.2.5 on 2023-11-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operating_date', models.DateTimeField()),
                ('Airline', models.CharField(max_length=20)),
                ('Airline_name', models.CharField(max_length=20)),
                ('Airline_NO', models.IntegerField(verbose_name=10)),
                ('Depature_Port', models.CharField(max_length=10)),
                ('Depature_Date_time', models.DateTimeField()),
                ('Arrival_Date_Time', models.DateField()),
                ('Flight_status', models.CharField(max_length=10)),
                ('Delay_issue', models.CharField(max_length=10)),
                ('Remarks', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight', models.CharField(max_length=20)),
                ('Service_status', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
                ('Depature_Port', models.CharField(max_length=10)),
                ('Arrival_Port', models.CharField(max_length=10)),
                ('Depature_Date_time', models.DateTimeField()),
                ('Arrival_Date_Time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='journeysearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField(verbose_name=5)),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.IntegerField(verbose_name=10)),
                ('Father', models.CharField(max_length=20)),
                ('Passport', models.IntegerField(verbose_name=10)),
                ('Gender', models.CharField(max_length=10)),
                ('FlightName', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=10)),
                ('Depature_Date_time', models.DateTimeField()),
                ('Arrival_Date_Time', models.DateField()),
                ('Risk_Satus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Riskaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField(verbose_name=5)),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.IntegerField(verbose_name=10)),
                ('Father', models.CharField(max_length=20)),
                ('Passport', models.IntegerField(verbose_name=10)),
                ('Gender', models.CharField(max_length=10)),
                ('NRC', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight', models.CharField(max_length=20)),
                ('TimeFrame', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.IntegerField(verbose_name=10)),
                ('NRC', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=6)),
                ('Depature_Port', models.CharField(max_length=10)),
                ('Depature_Date_time', models.DateTimeField()),
                ('Arrival_Port', models.CharField(max_length=10)),
                ('Arrival_Date_Time', models.DateField()),
            ],
        ),
    ]
